[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
buildCommand = "cd backend && npm ci && DATABASE_URL='postgresql://user:pass@localhost/db' npx prisma generate && npm run build"
startCommand = "cd backend && npx prisma migrate deploy && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 3
internalPort = 3000

[[services]]
name = "frontend"
buildCommand = "cd frontend && npm ci --legacy-peer-deps && CI=false npm run build"
startCommand = "npx serve -s frontend/build -l 3001"
healthcheckPath = "/"
healthcheckTimeout = 3
internalPort = 3001